import Foundation

/// What the shell does with a navigation the web content requested.
enum NavigationDecision: Equatable {
    /// Load inside the terminal's web view.
    case allowInShell
    /// Present in the in-app secure browser (SFSafariViewController); the terminal stays loaded
    /// underneath and is restored untouched when the reader is dismissed.
    case openExternally
    /// Hand to the system (mailto:, tel:, sms:, other app schemes).
    case openInSystem
    /// Drop it.
    case cancel
}

/// Pure, testable navigation policy. Market Terminal origins stay in the shell; everything else
/// (news articles, filings, exchange pages, company sites, research sources) leaves it.
struct NavigationPolicy: Equatable {
    /// Lower-cased hosts that count as Market Terminal.
    let internalHosts: Set<String>

    static let systemSchemes: Set<String> = ["mailto", "tel", "sms", "facetime", "facetime-audio", "maps", "itms-apps", "itms-appss"]
    static let blockedSchemes: Set<String> = ["javascript", "file", "ftp"]

    init(internalHosts: Set<String>) {
        self.internalHosts = Set(internalHosts.map { $0.lowercased() })
    }

    init(config: AppConfig) {
        self.init(internalHosts: config.internalHosts)
    }

    func isInternal(_ url: URL) -> Bool {
        guard let host = url.host?.lowercased() else { return false }
        return internalHosts.contains(host)
    }

    /// - Parameters:
    ///   - url: the navigation target.
    ///   - isMainFrame: `true` for top-level navigations, `false` for iframes (map embeds, webcams).
    ///   - opensNewWindow: `true` for `target=_blank` / `window.open` requests (no target frame).
    func decision(for url: URL, isMainFrame: Bool, opensNewWindow: Bool) -> NavigationDecision {
        let scheme = url.scheme?.lowercased() ?? ""

        if scheme.isEmpty || scheme == "about" || scheme == "blob" || scheme == "data" {
            // about:blank, blob: downloads generated by the page, inline data URIs.
            return opensNewWindow ? .cancel : .allowInShell
        }
        if Self.blockedSchemes.contains(scheme) { return .cancel }
        if scheme == DeepLinkRouter.scheme { return .cancel }   // never bounce through ourselves
        if Self.systemSchemes.contains(scheme) { return .openInSystem }

        guard scheme == "http" || scheme == "https" else {
            // Unknown custom scheme: let the system decide (it no-ops without a handler).
            return .openInSystem
        }

        if isInternal(url) {
            // Internal links always stay inside, even when the page asked for a new window.
            return .allowInShell
        }
        if opensNewWindow || isMainFrame {
            return .openExternally
        }
        // Third-party iframe content (Windy webcams, map embeds) renders in place.
        return .allowInShell
    }
}
